version: '0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration:
  - Release
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Genexcel/Genexcel.csproj --verbosity m
build_script:
  - cmd: dotnet pack
after_build:
  # For once the build has completed