version: '0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration:
  - Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Genexcel/Genexcel.csproj --verbosity m
build_script:
  - cmd: dotnet pack
after_build:
  # For once the build has completed
artifacts:
- path: ./src/Genexcel/bin/Release/*.nupkg
  name: nupkg
deploy:
  provider: NuGet
  api_key:
    secure: L8D5pckZ0KseUtlex1nSj8gjAyMeIichvxNd+KXccWqilYLoai/YZgwROnSei5xi
  skip_symbols: false
  artifact: nupkg